spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username: 
    password: 

server:
  port: 8085
